// This file is automatically generated by `Build.ps1 generate-scripts`.

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildFeatures.*
import jetbrains.buildServer.configs.kotlin.buildSteps.*
import jetbrains.buildServer.configs.kotlin.failureConditions.*
import jetbrains.buildServer.configs.kotlin.triggers.*
import jetbrains.buildServer.configs.kotlin.projectFeatures.*

version = "2025.11"

project {

    buildType(DebugBuild)
    buildType(ReleaseBuild)
    buildType(PublicBuild)
    buildType(PublicDeployment)

    buildTypesOrder = arrayListOf(DebugBuild,ReleaseBuild,PublicBuild,PublicDeployment)

    subProject(DockerTests)

    subProjectsOrder = arrayListOf(DockerTests)

}

object DebugBuild : BuildType({

    name = "Build [Debug]"

    artifactRules = """+:artifacts/publish/public/**/*=>artifacts/publish/public
+:artifacts/publish/private/**/*=>artifacts/publish/private
+:artifacts/testResults/**/*=>artifacts/testResults
+:artifacts/logs/**/*=>logs
+:artifacts/dumps/**/*=>dumps
"""

    params {
        text(
            "Build.Arguments", 
            "", 
            label ="DockerBuild.ps1 Arguments",
            description = "Arguments to append to the 'Build' build step.", allowEmpty = true)
        param("Build.Timeout", "30")
    }

    vcs {
        root(AbsoluteId("Backstage_Backstage20270"))
     checkoutMode = CheckoutMode.ON_AGENT
    }

    steps {
        powerShell {
            name = "Clean NuGet cache of produced and dependency packages"
            id = "CleanNuGetCache"
            edition = PowerShellStep.Edition.Core
            scriptMode = script {
                content = "${'$'}nugetPackages = if ( ${'$'}env:NUGET_PACKAGES ) { ${'$'}env:NUGET_PACKAGES } else { Join-Path ${'$'}HOME '.nuget' 'packages' }; ${'$'}removedDirs = 0; ${'$'}removedFiles = 0; if ( Test-Path -LiteralPath ${'$'}nugetPackages ) { foreach ( ${'$'}pattern in @('metalama.backstage*', 'postsharp.backstage*', 'postsharp.engineering', 'postsharp.engineering.*', 'sharpcrafters.backstage*', 'sharpcrafters.common*') ) { Get-ChildItem -LiteralPath ${'$'}nugetPackages -Directory -Filter ${'$'}pattern -ErrorAction SilentlyContinue | ForEach-Object { ${'$'}files = @( Get-ChildItem -LiteralPath ${'$'}_.FullName -Recurse -File -ErrorAction SilentlyContinue ).Count; Write-Host \"Removing NuGet cache directory: ${'$'}(${'$'}_.FullName) (${'$'}files file(s))\"; Remove-Item -LiteralPath ${'$'}_.FullName -Recurse -Force -ErrorAction SilentlyContinue; if ( -not ( Test-Path -LiteralPath ${'$'}_.FullName ) ) { ${'$'}removedDirs++; ${'$'}removedFiles += ${'$'}files } } } Write-Host \"Removed ${'$'}removedDirs package directory(ies) and ${'$'}removedFiles file(s) from the NuGet cache.\"; } else { Write-Host \"NuGet packages folder not found: ${'$'}nugetPackages\" }"
            }
            noProfile = false
        }
        powerShell {
            name = "Prepare Docker image backstage-2027.0"
            id = "PrepareImage"
            edition = PowerShellStep.Edition.Core
            scriptMode = file {
                path = "DockerBuild.ps1"
            }
            noProfile = false
            scriptArgs = "-BuildImage -ImageName backstage-2027.0 "
        }
        powerShell {
            name = "Build"
            id = "Build"
            edition = PowerShellStep.Edition.Core
            scriptMode = file {
                path = "DockerBuild.ps1"
            }
            noProfile = false
            scriptArgs = "-Script Build.ps1 -ImageName backstage-2027.0 -NoBuildImage -Label %system.teamcity.buildType.id%_%build.number% test --configuration Debug --buildNumber %build.number% --buildType %system.teamcity.buildType.id% --timeout %Build.Timeout% %Build.Arguments%"
        }
        powerShell {
            name = "Cleanup Docker containers"
            id = "DockerCleanup"
            executionMode = BuildStep.ExecutionMode.ALWAYS
            edition = PowerShellStep.Edition.Core
            scriptMode = script {
                content = "${'$'}label = \"%system.teamcity.buildType.id%_%build.number%\"; ${'$'}ids = docker ps -a -q --filter \"label=postsharp.build=${'$'}label\"; if (${'$'}ids) { docker rm -f ${'$'}ids 2>&1 | Out-Null }; if (${'$'}env:BUILDAGENT_CLEANUP_SCRIPT) { Write-Host \"Running the agent cleanup script: ${'$'}(${'$'}env:BUILDAGENT_CLEANUP_SCRIPT)\"; try { Invoke-Expression ${'$'}env:BUILDAGENT_CLEANUP_SCRIPT; if (${'$'}LASTEXITCODE -ne 0) { Write-Host \"The agent cleanup script exited with code ${'$'}LASTEXITCODE.\" } } catch { Write-Host \"The agent cleanup script failed: ${'$'}_\" } }"
            }
            noProfile = false
        }
    }

    requirements {
        matches("teamcity.agent.jvm.os.family", "Windows")
        matches("teamcity.agent.jvm.os.arch", "amd64")
        equals("env.BuildAgentType", "docker-win-x64-md")
    }

    features {
        swabra {
            filesCleanup = Swabra.FilesCleanup.BEFORE_BUILD
            lockingProcesses = Swabra.LockingProcessPolicy.KILL
            verbose = true
        }
        gitHubAppBuildScopedToken {
            parameterName = "env.GITHUB_TOKEN"
            connectionId = "%GITHUB_CONNECTION_POSTSHARP_OPS%"
            targetRepositories = "SharpCrafters.Backstage"
        }
        commitStatusPublisher {
            vcsRootExtId = "Backstage_Backstage20270"
            publisher = github {
                githubUrl = "https://api.github.com"
                authType = vcsRoot()
            }
        }
        pullRequests {
            vcsRootExtId = "Backstage_Backstage20270"
            provider = github {
                authType = vcsRoot()
                filterTargetBranch = "+:refs/heads/develop/2027.0"
                filterAuthorRole = PullRequests.GitHubRoleFilter.EVERYBODY
            }
        }
    }

    triggers {
        vcs {
            watchChangesInDependencies = true
            branchFilter = "+:develop/2027.0"
             quietPeriodMode = VcsTrigger.QuietPeriodMode.USE_CUSTOM
             quietPeriod = 7200
            // Build will not trigger automatically if the commit message contains comment value.
            triggerRules = "-:comment=<<VERSION_BUMP>>|<<DEPENDENCIES_UPDATED>>:**"
        }
    }

})

object ReleaseBuild : BuildType({

    name = "Build [Release]"

    artifactRules = """+:artifacts/publish/public/**/*=>artifacts/publish/public
+:artifacts/publish/private/**/*=>artifacts/publish/private
+:artifacts/testResults/**/*=>artifacts/testResults
+:artifacts/logs/**/*=>logs
+:artifacts/dumps/**/*=>dumps
"""

    params {
        text(
            "Build.Arguments", 
            "", 
            label ="DockerBuild.ps1 Arguments",
            description = "Arguments to append to the 'Build' build step.", allowEmpty = true)
        param("Build.Timeout", "30")
    }

    vcs {
        root(AbsoluteId("Backstage_Backstage20270"))
     checkoutMode = CheckoutMode.ON_AGENT
    }

    steps {
        powerShell {
            name = "Clean NuGet cache of produced and dependency packages"
            id = "CleanNuGetCache"
            edition = PowerShellStep.Edition.Core
            scriptMode = script {
                content = "${'$'}nugetPackages = if ( ${'$'}env:NUGET_PACKAGES ) { ${'$'}env:NUGET_PACKAGES } else { Join-Path ${'$'}HOME '.nuget' 'packages' }; ${'$'}removedDirs = 0; ${'$'}removedFiles = 0; if ( Test-Path -LiteralPath ${'$'}nugetPackages ) { foreach ( ${'$'}pattern in @('metalama.backstage*', 'postsharp.backstage*', 'postsharp.engineering', 'postsharp.engineering.*', 'sharpcrafters.backstage*', 'sharpcrafters.common*') ) { Get-ChildItem -LiteralPath ${'$'}nugetPackages -Directory -Filter ${'$'}pattern -ErrorAction SilentlyContinue | ForEach-Object { ${'$'}files = @( Get-ChildItem -LiteralPath ${'$'}_.FullName -Recurse -File -ErrorAction SilentlyContinue ).Count; Write-Host \"Removing NuGet cache directory: ${'$'}(${'$'}_.FullName) (${'$'}files file(s))\"; Remove-Item -LiteralPath ${'$'}_.FullName -Recurse -Force -ErrorAction SilentlyContinue; if ( -not ( Test-Path -LiteralPath ${'$'}_.FullName ) ) { ${'$'}removedDirs++; ${'$'}removedFiles += ${'$'}files } } } Write-Host \"Removed ${'$'}removedDirs package directory(ies) and ${'$'}removedFiles file(s) from the NuGet cache.\"; } else { Write-Host \"NuGet packages folder not found: ${'$'}nugetPackages\" }"
            }
            noProfile = false
        }
        powerShell {
            name = "Prepare Docker image backstage-2027.0"
            id = "PrepareImage"
            edition = PowerShellStep.Edition.Core
            scriptMode = file {
                path = "DockerBuild.ps1"
            }
            noProfile = false
            scriptArgs = "-BuildImage -ImageName backstage-2027.0 "
        }
        powerShell {
            name = "Build"
            id = "Build"
            edition = PowerShellStep.Edition.Core
            scriptMode = file {
                path = "DockerBuild.ps1"
            }
            noProfile = false
            scriptArgs = "-Script Build.ps1 -ImageName backstage-2027.0 -NoBuildImage -Label %system.teamcity.buildType.id%_%build.number% test --configuration Release --buildNumber %build.number% --buildType %system.teamcity.buildType.id% --timeout %Build.Timeout% %Build.Arguments%"
        }
        powerShell {
            name = "Cleanup Docker containers"
            id = "DockerCleanup"
            executionMode = BuildStep.ExecutionMode.ALWAYS
            edition = PowerShellStep.Edition.Core
            scriptMode = script {
                content = "${'$'}label = \"%system.teamcity.buildType.id%_%build.number%\"; ${'$'}ids = docker ps -a -q --filter \"label=postsharp.build=${'$'}label\"; if (${'$'}ids) { docker rm -f ${'$'}ids 2>&1 | Out-Null }; if (${'$'}env:BUILDAGENT_CLEANUP_SCRIPT) { Write-Host \"Running the agent cleanup script: ${'$'}(${'$'}env:BUILDAGENT_CLEANUP_SCRIPT)\"; try { Invoke-Expression ${'$'}env:BUILDAGENT_CLEANUP_SCRIPT; if (${'$'}LASTEXITCODE -ne 0) { Write-Host \"The agent cleanup script exited with code ${'$'}LASTEXITCODE.\" } } catch { Write-Host \"The agent cleanup script failed: ${'$'}_\" } }"
            }
            noProfile = false
        }
    }

    requirements {
        matches("teamcity.agent.jvm.os.family", "Windows")
        matches("teamcity.agent.jvm.os.arch", "amd64")
        equals("env.BuildAgentType", "docker-win-x64-md")
    }

    features {
        swabra {
            filesCleanup = Swabra.FilesCleanup.BEFORE_BUILD
            lockingProcesses = Swabra.LockingProcessPolicy.KILL
            verbose = true
        }
        gitHubAppBuildScopedToken {
            parameterName = "env.GITHUB_TOKEN"
            connectionId = "%GITHUB_CONNECTION_POSTSHARP_OPS%"
            targetRepositories = "SharpCrafters.Backstage"
        }
        commitStatusPublisher {
            vcsRootExtId = "Backstage_Backstage20270"
            publisher = github {
                githubUrl = "https://api.github.com"
                authType = vcsRoot()
            }
        }
        pullRequests {
            vcsRootExtId = "Backstage_Backstage20270"
            provider = github {
                authType = vcsRoot()
                filterTargetBranch = "+:refs/heads/develop/2027.0"
                filterAuthorRole = PullRequests.GitHubRoleFilter.EVERYBODY
            }
        }
    }

})

object PublicBuild : BuildType({

    name = "Build [Public]"

    artifactRules = """+:artifacts/publish/public/**/*=>artifacts/publish/public
+:artifacts/publish/private/**/*=>artifacts/publish/private
+:artifacts/testResults/**/*=>artifacts/testResults
+:artifacts/logs/**/*=>logs
+:artifacts/dumps/**/*=>dumps
"""

    params {
        text(
            "Build.Arguments", 
            "", 
            label ="DockerBuild.ps1 Arguments",
            description = "Arguments to append to the 'Build' build step.", allowEmpty = true)
        param("Build.Timeout", "30")
    }

    vcs {
        root(AbsoluteId("Backstage_Backstage20270"))
     checkoutMode = CheckoutMode.ON_AGENT
    }

    steps {
        powerShell {
            name = "Clean NuGet cache of produced and dependency packages"
            id = "CleanNuGetCache"
            edition = PowerShellStep.Edition.Core
            scriptMode = script {
                content = "${'$'}nugetPackages = if ( ${'$'}env:NUGET_PACKAGES ) { ${'$'}env:NUGET_PACKAGES } else { Join-Path ${'$'}HOME '.nuget' 'packages' }; ${'$'}removedDirs = 0; ${'$'}removedFiles = 0; if ( Test-Path -LiteralPath ${'$'}nugetPackages ) { foreach ( ${'$'}pattern in @('metalama.backstage*', 'postsharp.backstage*', 'postsharp.engineering', 'postsharp.engineering.*', 'sharpcrafters.backstage*', 'sharpcrafters.common*') ) { Get-ChildItem -LiteralPath ${'$'}nugetPackages -Directory -Filter ${'$'}pattern -ErrorAction SilentlyContinue | ForEach-Object { ${'$'}files = @( Get-ChildItem -LiteralPath ${'$'}_.FullName -Recurse -File -ErrorAction SilentlyContinue ).Count; Write-Host \"Removing NuGet cache directory: ${'$'}(${'$'}_.FullName) (${'$'}files file(s))\"; Remove-Item -LiteralPath ${'$'}_.FullName -Recurse -Force -ErrorAction SilentlyContinue; if ( -not ( Test-Path -LiteralPath ${'$'}_.FullName ) ) { ${'$'}removedDirs++; ${'$'}removedFiles += ${'$'}files } } } Write-Host \"Removed ${'$'}removedDirs package directory(ies) and ${'$'}removedFiles file(s) from the NuGet cache.\"; } else { Write-Host \"NuGet packages folder not found: ${'$'}nugetPackages\" }"
            }
            noProfile = false
        }
        powerShell {
            name = "Prepare Docker image backstage-2027.0"
            id = "PrepareImage"
            edition = PowerShellStep.Edition.Core
            scriptMode = file {
                path = "DockerBuild.ps1"
            }
            noProfile = false
            scriptArgs = "-BuildImage -ImageName backstage-2027.0 "
        }
        powerShell {
            name = "Build"
            id = "Build"
            edition = PowerShellStep.Edition.Core
            scriptMode = file {
                path = "DockerBuild.ps1"
            }
            noProfile = false
            scriptArgs = "-Script Build.ps1 -ImageName backstage-2027.0 -NoBuildImage -Label %system.teamcity.buildType.id%_%build.number% test --configuration Public --buildNumber %build.number% --buildType %system.teamcity.buildType.id% --timeout %Build.Timeout% %Build.Arguments%"
        }
        powerShell {
            name = "Cleanup Docker containers"
            id = "DockerCleanup"
            executionMode = BuildStep.ExecutionMode.ALWAYS
            edition = PowerShellStep.Edition.Core
            scriptMode = script {
                content = "${'$'}label = \"%system.teamcity.buildType.id%_%build.number%\"; ${'$'}ids = docker ps -a -q --filter \"label=postsharp.build=${'$'}label\"; if (${'$'}ids) { docker rm -f ${'$'}ids 2>&1 | Out-Null }; if (${'$'}env:BUILDAGENT_CLEANUP_SCRIPT) { Write-Host \"Running the agent cleanup script: ${'$'}(${'$'}env:BUILDAGENT_CLEANUP_SCRIPT)\"; try { Invoke-Expression ${'$'}env:BUILDAGENT_CLEANUP_SCRIPT; if (${'$'}LASTEXITCODE -ne 0) { Write-Host \"The agent cleanup script exited with code ${'$'}LASTEXITCODE.\" } } catch { Write-Host \"The agent cleanup script failed: ${'$'}_\" } }"
            }
            noProfile = false
        }
    }

    requirements {
        matches("teamcity.agent.jvm.os.family", "Windows")
        matches("teamcity.agent.jvm.os.arch", "amd64")
        equals("env.BuildAgentType", "docker-win-x64-md")
    }

    features {
        swabra {
            filesCleanup = Swabra.FilesCleanup.BEFORE_BUILD
            lockingProcesses = Swabra.LockingProcessPolicy.KILL
            verbose = true
        }
        gitHubAppBuildScopedToken {
            parameterName = "env.GITHUB_TOKEN"
            connectionId = "%GITHUB_CONNECTION_POSTSHARP_OPS%"
            targetRepositories = "SharpCrafters.Backstage"
        }
        commitStatusPublisher {
            vcsRootExtId = "Backstage_Backstage20270"
            publisher = github {
                githubUrl = "https://api.github.com"
                authType = vcsRoot()
            }
        }
        pullRequests {
            vcsRootExtId = "Backstage_Backstage20270"
            provider = github {
                authType = vcsRoot()
                filterTargetBranch = "+:refs/heads/develop/2027.0"
                filterAuthorRole = PullRequests.GitHubRoleFilter.EVERYBODY
            }
        }
    }

})

object PublicDeployment : BuildType({

    name = "Deploy [Public]"

    type = Type.DEPLOYMENT

    params {
        text(
            "Publish.Arguments", 
            "", 
            label ="DockerBuild.ps1 Arguments",
            description = "Arguments to append to the 'Publish' build step.", allowEmpty = true)
        param("Publish.Timeout", "30")
    }

    vcs {
        root(AbsoluteId("Backstage_Backstage20270"))
     checkoutMode = CheckoutMode.ON_AGENT
    }

    steps {
        powerShell {
            name = "Clean NuGet cache of produced and dependency packages"
            id = "CleanNuGetCache"
            edition = PowerShellStep.Edition.Core
            scriptMode = script {
                content = "${'$'}nugetPackages = if ( ${'$'}env:NUGET_PACKAGES ) { ${'$'}env:NUGET_PACKAGES } else { Join-Path ${'$'}HOME '.nuget' 'packages' }; ${'$'}removedDirs = 0; ${'$'}removedFiles = 0; if ( Test-Path -LiteralPath ${'$'}nugetPackages ) { foreach ( ${'$'}pattern in @('metalama.backstage*', 'postsharp.backstage*', 'postsharp.engineering', 'postsharp.engineering.*', 'sharpcrafters.backstage*', 'sharpcrafters.common*') ) { Get-ChildItem -LiteralPath ${'$'}nugetPackages -Directory -Filter ${'$'}pattern -ErrorAction SilentlyContinue | ForEach-Object { ${'$'}files = @( Get-ChildItem -LiteralPath ${'$'}_.FullName -Recurse -File -ErrorAction SilentlyContinue ).Count; Write-Host \"Removing NuGet cache directory: ${'$'}(${'$'}_.FullName) (${'$'}files file(s))\"; Remove-Item -LiteralPath ${'$'}_.FullName -Recurse -Force -ErrorAction SilentlyContinue; if ( -not ( Test-Path -LiteralPath ${'$'}_.FullName ) ) { ${'$'}removedDirs++; ${'$'}removedFiles += ${'$'}files } } } Write-Host \"Removed ${'$'}removedDirs package directory(ies) and ${'$'}removedFiles file(s) from the NuGet cache.\"; } else { Write-Host \"NuGet packages folder not found: ${'$'}nugetPackages\" }"
            }
            noProfile = false
        }
        powerShell {
            name = "Prepare Docker image backstage-2027.0"
            id = "PrepareImage"
            edition = PowerShellStep.Edition.Core
            scriptMode = file {
                path = "DockerBuild.ps1"
            }
            noProfile = false
            scriptArgs = "-BuildImage -ImageName backstage-2027.0 "
        }
        powerShell {
            name = "Publish"
            id = "Publish"
            edition = PowerShellStep.Edition.Core
            scriptMode = file {
                path = "DockerBuild.ps1"
            }
            noProfile = false
            scriptArgs = "-Script Build.ps1 -ImageName backstage-2027.0 -NoBuildImage -Label %system.teamcity.buildType.id%_%build.number% publish --configuration Public --deployment default --timeout %Publish.Timeout% %Publish.Arguments%"
        }
        powerShell {
            name = "Cleanup Docker containers"
            id = "DockerCleanup"
            executionMode = BuildStep.ExecutionMode.ALWAYS
            edition = PowerShellStep.Edition.Core
            scriptMode = script {
                content = "${'$'}label = \"%system.teamcity.buildType.id%_%build.number%\"; ${'$'}ids = docker ps -a -q --filter \"label=postsharp.build=${'$'}label\"; if (${'$'}ids) { docker rm -f ${'$'}ids 2>&1 | Out-Null }; if (${'$'}env:BUILDAGENT_CLEANUP_SCRIPT) { Write-Host \"Running the agent cleanup script: ${'$'}(${'$'}env:BUILDAGENT_CLEANUP_SCRIPT)\"; try { Invoke-Expression ${'$'}env:BUILDAGENT_CLEANUP_SCRIPT; if (${'$'}LASTEXITCODE -ne 0) { Write-Host \"The agent cleanup script exited with code ${'$'}LASTEXITCODE.\" } } catch { Write-Host \"The agent cleanup script failed: ${'$'}_\" } }"
            }
            noProfile = false
        }
    }

    requirements {
        matches("teamcity.agent.jvm.os.family", "Windows")
        matches("teamcity.agent.jvm.os.arch", "amd64")
        equals("env.BuildAgentType", "docker-win-x64-md")
    }

    features {
        swabra {
            filesCleanup = Swabra.FilesCleanup.BEFORE_BUILD
            lockingProcesses = Swabra.LockingProcessPolicy.KILL
            verbose = true
        }
        gitHubAppBuildScopedToken {
            parameterName = "env.GITHUB_TOKEN"
            connectionId = "%GITHUB_CONNECTION_POSTSHARP_OPS%"
            targetRepositories = "SharpCrafters.Backstage"
        }
    }

    dependencies {
        snapshot(PublicBuild) {
                 onDependencyFailure = FailureAction.FAIL_TO_START
        }

        artifacts(PublicBuild) { 
            cleanDestination = true
            artifactRules = "+:artifacts/publish/public/**/*=>artifacts/publish/public\n+:artifacts/publish/private/**/*=>artifacts/publish/private"
        }
     }

})

object DockerTestsWindowsX64 : BuildType({

    name = "Docker Tests (Windows x64)"

    params {
        text(
            "Exec.Arguments", 
            "", 
            label ="eng/RunDockerTests.ps1 Arguments",
            description = "Arguments to append to the 'Execute eng/RunDockerTests.ps1' build step.", allowEmpty = true)
    }

    vcs {
        root(AbsoluteId("Backstage_Backstage20270"))
     checkoutMode = CheckoutMode.ON_AGENT
    }

    steps {
        powerShell {
            name = "Clean NuGet cache of produced and dependency packages"
            id = "CleanNuGetCache"
            edition = PowerShellStep.Edition.Core
            scriptMode = script {
                content = "${'$'}nugetPackages = if ( ${'$'}env:NUGET_PACKAGES ) { ${'$'}env:NUGET_PACKAGES } else { Join-Path ${'$'}HOME '.nuget' 'packages' }; ${'$'}removedDirs = 0; ${'$'}removedFiles = 0; if ( Test-Path -LiteralPath ${'$'}nugetPackages ) { foreach ( ${'$'}pattern in @('metalama.backstage*', 'postsharp.backstage*', 'postsharp.engineering', 'postsharp.engineering.*', 'sharpcrafters.backstage*', 'sharpcrafters.common*') ) { Get-ChildItem -LiteralPath ${'$'}nugetPackages -Directory -Filter ${'$'}pattern -ErrorAction SilentlyContinue | ForEach-Object { ${'$'}files = @( Get-ChildItem -LiteralPath ${'$'}_.FullName -Recurse -File -ErrorAction SilentlyContinue ).Count; Write-Host \"Removing NuGet cache directory: ${'$'}(${'$'}_.FullName) (${'$'}files file(s))\"; Remove-Item -LiteralPath ${'$'}_.FullName -Recurse -Force -ErrorAction SilentlyContinue; if ( -not ( Test-Path -LiteralPath ${'$'}_.FullName ) ) { ${'$'}removedDirs++; ${'$'}removedFiles += ${'$'}files } } } Write-Host \"Removed ${'$'}removedDirs package directory(ies) and ${'$'}removedFiles file(s) from the NuGet cache.\"; } else { Write-Host \"NuGet packages folder not found: ${'$'}nugetPackages\" }"
            }
            noProfile = false
        }
        powerShell {
            name = "Copy nuget.restored.config to nuget.config"
            id = "CopyNuGetConfig"
            edition = PowerShellStep.Edition.Core
            scriptMode = script {
                content = "Copy-Item -Path \"artifacts/publish/private/nuget.restored.config\" -Destination \"nuget.config\" -Force;Copy-Item -Path \"artifacts/publish/private/nuget.restored.config\" -Destination \"nuget.wsl.config\" -Force;"
            }
            noProfile = false
        }
        powerShell {
            name = "Create eng/Versions.g.props"
            id = "CreateVersionsFile"
            edition = PowerShellStep.Edition.Core
            scriptMode = script {
                content = "New-Item -Path \"eng/Versions.g.props\" -ItemType File -Force -Value \"<Project><Import Project=`\"../artifacts/publish/private/Backstage.version.props`\" /></Project>\" | Out-Null;"
            }
            noProfile = false
        }
        powerShell {
            name = "Execute eng/RunDockerTests.ps1"
            id = "Exec"
            edition = PowerShellStep.Edition.Core
            scriptMode = file {
                path = "eng/RunDockerTests.ps1"
            }
            noProfile = false
            scriptArgs = "-Platform win-x64 %Exec.Arguments%"
        }
        powerShell {
            name = "Cleanup Docker containers"
            id = "DockerCleanup"
            executionMode = BuildStep.ExecutionMode.ALWAYS
            edition = PowerShellStep.Edition.Core
            scriptMode = script {
                content = "${'$'}label = \"%system.teamcity.buildType.id%_%build.number%\"; ${'$'}ids = docker ps -a -q --filter \"label=postsharp.build=${'$'}label\"; if (${'$'}ids) { docker rm -f ${'$'}ids 2>&1 | Out-Null }; if (${'$'}env:BUILDAGENT_CLEANUP_SCRIPT) { Write-Host \"Running the agent cleanup script: ${'$'}(${'$'}env:BUILDAGENT_CLEANUP_SCRIPT)\"; try { Invoke-Expression ${'$'}env:BUILDAGENT_CLEANUP_SCRIPT; if (${'$'}LASTEXITCODE -ne 0) { Write-Host \"The agent cleanup script exited with code ${'$'}LASTEXITCODE.\" } } catch { Write-Host \"The agent cleanup script failed: ${'$'}_\" } }"
            }
            noProfile = false
        }
    }

    requirements {
        matches("teamcity.agent.jvm.os.family", "Windows")
        doesNotContain("env.PROCESSOR_IDENTIFIER", "ARMv8")
    }

    features {
        swabra {
            filesCleanup = Swabra.FilesCleanup.BEFORE_BUILD
            lockingProcesses = Swabra.LockingProcessPolicy.KILL
            verbose = true
        }
        gitHubAppBuildScopedToken {
            parameterName = "env.GITHUB_TOKEN"
            connectionId = "%GITHUB_CONNECTION_POSTSHARP_OPS%"
            targetRepositories = "SharpCrafters.Backstage"
        }
    }

    dependencies {
        snapshot(DebugBuild) {
                 onDependencyFailure = FailureAction.FAIL_TO_START
        }

        artifacts(DebugBuild) { 
            cleanDestination = true
            artifactRules = "+:artifacts/publish/private/**/*=>artifacts/publish/private"
        }
     }

})

object DockerTestsLinuxX64 : BuildType({

    name = "Docker Tests (Linux x64)"

    params {
        text(
            "Exec.Arguments", 
            "", 
            label ="eng/RunDockerTests.ps1 Arguments",
            description = "Arguments to append to the 'Execute eng/RunDockerTests.ps1' build step.", allowEmpty = true)
    }

    vcs {
        root(AbsoluteId("Backstage_Backstage20270"))
     checkoutMode = CheckoutMode.ON_AGENT
    }

    steps {
        powerShell {
            name = "Clean NuGet cache of produced and dependency packages"
            id = "CleanNuGetCache"
            edition = PowerShellStep.Edition.Core
            scriptMode = script {
                content = "${'$'}nugetPackages = if ( ${'$'}env:NUGET_PACKAGES ) { ${'$'}env:NUGET_PACKAGES } else { Join-Path ${'$'}HOME '.nuget' 'packages' }; ${'$'}removedDirs = 0; ${'$'}removedFiles = 0; if ( Test-Path -LiteralPath ${'$'}nugetPackages ) { foreach ( ${'$'}pattern in @('metalama.backstage*', 'postsharp.backstage*', 'postsharp.engineering', 'postsharp.engineering.*', 'sharpcrafters.backstage*', 'sharpcrafters.common*') ) { Get-ChildItem -LiteralPath ${'$'}nugetPackages -Directory -Filter ${'$'}pattern -ErrorAction SilentlyContinue | ForEach-Object { ${'$'}files = @( Get-ChildItem -LiteralPath ${'$'}_.FullName -Recurse -File -ErrorAction SilentlyContinue ).Count; Write-Host \"Removing NuGet cache directory: ${'$'}(${'$'}_.FullName) (${'$'}files file(s))\"; Remove-Item -LiteralPath ${'$'}_.FullName -Recurse -Force -ErrorAction SilentlyContinue; if ( -not ( Test-Path -LiteralPath ${'$'}_.FullName ) ) { ${'$'}removedDirs++; ${'$'}removedFiles += ${'$'}files } } } Write-Host \"Removed ${'$'}removedDirs package directory(ies) and ${'$'}removedFiles file(s) from the NuGet cache.\"; } else { Write-Host \"NuGet packages folder not found: ${'$'}nugetPackages\" }"
            }
            noProfile = false
        }
        powerShell {
            name = "Copy nuget.restored.config to nuget.config"
            id = "CopyNuGetConfig"
            edition = PowerShellStep.Edition.Core
            scriptMode = script {
                content = "Copy-Item -Path \"artifacts/publish/private/nuget.restored.config\" -Destination \"nuget.config\" -Force;Copy-Item -Path \"artifacts/publish/private/nuget.restored.config\" -Destination \"nuget.wsl.config\" -Force;"
            }
            noProfile = false
        }
        powerShell {
            name = "Create eng/Versions.g.props"
            id = "CreateVersionsFile"
            edition = PowerShellStep.Edition.Core
            scriptMode = script {
                content = "New-Item -Path \"eng/Versions.g.props\" -ItemType File -Force -Value \"<Project><Import Project=`\"../artifacts/publish/private/Backstage.version.props`\" /></Project>\" | Out-Null;"
            }
            noProfile = false
        }
        powerShell {
            name = "Execute eng/RunDockerTests.ps1"
            id = "Exec"
            edition = PowerShellStep.Edition.Core
            scriptMode = file {
                path = "eng/RunDockerTests.ps1"
            }
            noProfile = false
            scriptArgs = "-Platform linux-x64 %Exec.Arguments%"
        }
        powerShell {
            name = "Cleanup Docker containers"
            id = "DockerCleanup"
            executionMode = BuildStep.ExecutionMode.ALWAYS
            edition = PowerShellStep.Edition.Core
            scriptMode = script {
                content = "${'$'}label = \"%system.teamcity.buildType.id%_%build.number%\"; ${'$'}ids = docker ps -a -q --filter \"label=postsharp.build=${'$'}label\"; if (${'$'}ids) { docker rm -f ${'$'}ids 2>&1 | Out-Null }; if (${'$'}env:BUILDAGENT_CLEANUP_SCRIPT) { Write-Host \"Running the agent cleanup script: ${'$'}(${'$'}env:BUILDAGENT_CLEANUP_SCRIPT)\"; try { Invoke-Expression ${'$'}env:BUILDAGENT_CLEANUP_SCRIPT; if (${'$'}LASTEXITCODE -ne 0) { Write-Host \"The agent cleanup script exited with code ${'$'}LASTEXITCODE.\" } } catch { Write-Host \"The agent cleanup script failed: ${'$'}_\" } }"
            }
            noProfile = false
        }
    }

    requirements {
        equals("teamcity.agent.jvm.os.name", "Linux")
        equals("teamcity.agent.jvm.os.arch", "amd64")
    }

    features {
        swabra {
            filesCleanup = Swabra.FilesCleanup.BEFORE_BUILD
            lockingProcesses = Swabra.LockingProcessPolicy.KILL
            verbose = true
        }
        gitHubAppBuildScopedToken {
            parameterName = "env.GITHUB_TOKEN"
            connectionId = "%GITHUB_CONNECTION_POSTSHARP_OPS%"
            targetRepositories = "SharpCrafters.Backstage"
        }
    }

    dependencies {
        snapshot(DebugBuild) {
                 onDependencyFailure = FailureAction.FAIL_TO_START
        }

        artifacts(DebugBuild) { 
            cleanDestination = true
            artifactRules = "+:artifacts/publish/private/**/*=>artifacts/publish/private"
        }
     }

})

object DockerTestsLinuxArm64 : BuildType({

    name = "Docker Tests (Linux ARM64)"

    params {
        text(
            "Exec.Arguments", 
            "", 
            label ="eng/RunDockerTests.ps1 Arguments",
            description = "Arguments to append to the 'Execute eng/RunDockerTests.ps1' build step.", allowEmpty = true)
    }

    vcs {
        root(AbsoluteId("Backstage_Backstage20270"))
     checkoutMode = CheckoutMode.ON_AGENT
    }

    steps {
        powerShell {
            name = "Clean NuGet cache of produced and dependency packages"
            id = "CleanNuGetCache"
            edition = PowerShellStep.Edition.Core
            scriptMode = script {
                content = "${'$'}nugetPackages = if ( ${'$'}env:NUGET_PACKAGES ) { ${'$'}env:NUGET_PACKAGES } else { Join-Path ${'$'}HOME '.nuget' 'packages' }; ${'$'}removedDirs = 0; ${'$'}removedFiles = 0; if ( Test-Path -LiteralPath ${'$'}nugetPackages ) { foreach ( ${'$'}pattern in @('metalama.backstage*', 'postsharp.backstage*', 'postsharp.engineering', 'postsharp.engineering.*', 'sharpcrafters.backstage*', 'sharpcrafters.common*') ) { Get-ChildItem -LiteralPath ${'$'}nugetPackages -Directory -Filter ${'$'}pattern -ErrorAction SilentlyContinue | ForEach-Object { ${'$'}files = @( Get-ChildItem -LiteralPath ${'$'}_.FullName -Recurse -File -ErrorAction SilentlyContinue ).Count; Write-Host \"Removing NuGet cache directory: ${'$'}(${'$'}_.FullName) (${'$'}files file(s))\"; Remove-Item -LiteralPath ${'$'}_.FullName -Recurse -Force -ErrorAction SilentlyContinue; if ( -not ( Test-Path -LiteralPath ${'$'}_.FullName ) ) { ${'$'}removedDirs++; ${'$'}removedFiles += ${'$'}files } } } Write-Host \"Removed ${'$'}removedDirs package directory(ies) and ${'$'}removedFiles file(s) from the NuGet cache.\"; } else { Write-Host \"NuGet packages folder not found: ${'$'}nugetPackages\" }"
            }
            noProfile = false
        }
        powerShell {
            name = "Copy nuget.restored.config to nuget.config"
            id = "CopyNuGetConfig"
            edition = PowerShellStep.Edition.Core
            scriptMode = script {
                content = "Copy-Item -Path \"artifacts/publish/private/nuget.restored.config\" -Destination \"nuget.config\" -Force;Copy-Item -Path \"artifacts/publish/private/nuget.restored.config\" -Destination \"nuget.wsl.config\" -Force;"
            }
            noProfile = false
        }
        powerShell {
            name = "Create eng/Versions.g.props"
            id = "CreateVersionsFile"
            edition = PowerShellStep.Edition.Core
            scriptMode = script {
                content = "New-Item -Path \"eng/Versions.g.props\" -ItemType File -Force -Value \"<Project><Import Project=`\"../artifacts/publish/private/Backstage.version.props`\" /></Project>\" | Out-Null;"
            }
            noProfile = false
        }
        powerShell {
            name = "Execute eng/RunDockerTests.ps1"
            id = "Exec"
            edition = PowerShellStep.Edition.Core
            scriptMode = file {
                path = "eng/RunDockerTests.ps1"
            }
            noProfile = false
            scriptArgs = "-Platform linux-arm64 %Exec.Arguments%"
        }
        powerShell {
            name = "Cleanup Docker containers"
            id = "DockerCleanup"
            executionMode = BuildStep.ExecutionMode.ALWAYS
            edition = PowerShellStep.Edition.Core
            scriptMode = script {
                content = "${'$'}label = \"%system.teamcity.buildType.id%_%build.number%\"; ${'$'}ids = docker ps -a -q --filter \"label=postsharp.build=${'$'}label\"; if (${'$'}ids) { docker rm -f ${'$'}ids 2>&1 | Out-Null }; if (${'$'}env:BUILDAGENT_CLEANUP_SCRIPT) { Write-Host \"Running the agent cleanup script: ${'$'}(${'$'}env:BUILDAGENT_CLEANUP_SCRIPT)\"; try { Invoke-Expression ${'$'}env:BUILDAGENT_CLEANUP_SCRIPT; if (${'$'}LASTEXITCODE -ne 0) { Write-Host \"The agent cleanup script exited with code ${'$'}LASTEXITCODE.\" } } catch { Write-Host \"The agent cleanup script failed: ${'$'}_\" } }"
            }
            noProfile = false
        }
    }

    requirements {
        matches("teamcity.agent.jvm.os.name", "Linux|Mac OS X")
        equals("teamcity.agent.jvm.os.arch", "aarch64")
    }

    features {
        swabra {
            filesCleanup = Swabra.FilesCleanup.BEFORE_BUILD
            lockingProcesses = Swabra.LockingProcessPolicy.KILL
            verbose = true
        }
        gitHubAppBuildScopedToken {
            parameterName = "env.GITHUB_TOKEN"
            connectionId = "%GITHUB_CONNECTION_POSTSHARP_OPS%"
            targetRepositories = "SharpCrafters.Backstage"
        }
    }

    dependencies {
        snapshot(DebugBuild) {
                 onDependencyFailure = FailureAction.FAIL_TO_START
        }

        artifacts(DebugBuild) { 
            cleanDestination = true
            artifactRules = "+:artifacts/publish/private/**/*=>artifacts/publish/private"
        }
     }

})

object RunAllDockerTests : BuildType({

    name = "Run All Docker Tests"

    type = Type.COMPOSITE

    vcs {
        root(AbsoluteId("Backstage_Backstage20270"))
        showDependenciesChanges = true
     checkoutMode = CheckoutMode.ON_AGENT
    }

    features {
        gitHubAppBuildScopedToken {
            parameterName = "env.GITHUB_TOKEN"
            connectionId = "%GITHUB_CONNECTION_POSTSHARP_OPS%"
            targetRepositories = "SharpCrafters.Backstage"
        }
    }

    dependencies {
        snapshot(DockerTestsWindowsX64) {
                 onDependencyFailure = FailureAction.FAIL_TO_START
        }
        snapshot(DockerTestsLinuxX64) {
                 onDependencyFailure = FailureAction.FAIL_TO_START
        }
        snapshot(DockerTestsLinuxArm64) {
                 onDependencyFailure = FailureAction.FAIL_TO_START
        }
     }

})

object PlatformTestsMacOSArm64 : BuildType({

    name = "Platform Tests (macOS ARM64)"

    params {
        text(
            "Exec.Arguments", 
            "", 
            label ="src/tests/Platform/RunMacOSTests.ps1 Arguments",
            description = "Arguments to append to the 'Execute src/tests/Platform/RunMacOSTests.ps1' build step.", allowEmpty = true)
    }

    vcs {
        root(AbsoluteId("Backstage_Backstage20270"))
     checkoutMode = CheckoutMode.ON_AGENT
    }

    steps {
        powerShell {
            name = "Clean NuGet cache of produced and dependency packages"
            id = "CleanNuGetCache"
            edition = PowerShellStep.Edition.Core
            scriptMode = script {
                content = "${'$'}nugetPackages = if ( ${'$'}env:NUGET_PACKAGES ) { ${'$'}env:NUGET_PACKAGES } else { Join-Path ${'$'}HOME '.nuget' 'packages' }; ${'$'}removedDirs = 0; ${'$'}removedFiles = 0; if ( Test-Path -LiteralPath ${'$'}nugetPackages ) { foreach ( ${'$'}pattern in @('metalama.backstage*', 'postsharp.backstage*', 'postsharp.engineering', 'postsharp.engineering.*', 'sharpcrafters.backstage*', 'sharpcrafters.common*') ) { Get-ChildItem -LiteralPath ${'$'}nugetPackages -Directory -Filter ${'$'}pattern -ErrorAction SilentlyContinue | ForEach-Object { ${'$'}files = @( Get-ChildItem -LiteralPath ${'$'}_.FullName -Recurse -File -ErrorAction SilentlyContinue ).Count; Write-Host \"Removing NuGet cache directory: ${'$'}(${'$'}_.FullName) (${'$'}files file(s))\"; Remove-Item -LiteralPath ${'$'}_.FullName -Recurse -Force -ErrorAction SilentlyContinue; if ( -not ( Test-Path -LiteralPath ${'$'}_.FullName ) ) { ${'$'}removedDirs++; ${'$'}removedFiles += ${'$'}files } } } Write-Host \"Removed ${'$'}removedDirs package directory(ies) and ${'$'}removedFiles file(s) from the NuGet cache.\"; } else { Write-Host \"NuGet packages folder not found: ${'$'}nugetPackages\" }"
            }
            noProfile = false
        }
        powerShell {
            name = "Copy nuget.restored.config to nuget.config"
            id = "CopyNuGetConfig"
            edition = PowerShellStep.Edition.Core
            scriptMode = script {
                content = "Copy-Item -Path \"artifacts/publish/private/nuget.restored.config\" -Destination \"nuget.config\" -Force;Copy-Item -Path \"artifacts/publish/private/nuget.restored.config\" -Destination \"nuget.wsl.config\" -Force;"
            }
            noProfile = false
        }
        powerShell {
            name = "Create eng/Versions.g.props"
            id = "CreateVersionsFile"
            edition = PowerShellStep.Edition.Core
            scriptMode = script {
                content = "New-Item -Path \"eng/Versions.g.props\" -ItemType File -Force -Value \"<Project><Import Project=`\"../artifacts/publish/private/Backstage.version.props`\" /></Project>\" | Out-Null;"
            }
            noProfile = false
        }
        powerShell {
            name = "Execute src/tests/Platform/RunMacOSTests.ps1"
            id = "Exec"
            edition = PowerShellStep.Edition.Core
            scriptMode = file {
                path = "src/tests/Platform/RunMacOSTests.ps1"
            }
            noProfile = false
            scriptArgs = " %Exec.Arguments%"
        }
    }

    requirements {
        equals("teamcity.agent.jvm.os.name", "Mac OS X")
        equals("teamcity.agent.jvm.os.arch", "aarch64")
    }

    features {
        swabra {
            filesCleanup = Swabra.FilesCleanup.BEFORE_BUILD
            lockingProcesses = Swabra.LockingProcessPolicy.KILL
            verbose = true
        }
        gitHubAppBuildScopedToken {
            parameterName = "env.GITHUB_TOKEN"
            connectionId = "%GITHUB_CONNECTION_POSTSHARP_OPS%"
            targetRepositories = "SharpCrafters.Backstage"
        }
    }

    dependencies {
        snapshot(DebugBuild) {
                 onDependencyFailure = FailureAction.FAIL_TO_START
        }

        artifacts(DebugBuild) { 
            cleanDestination = true
            artifactRules = "+:artifacts/publish/private/**/*=>artifacts/publish/private"
        }
     }

})

object DockerTests : Project({

    name = "Docker Tests"

    buildType(DockerTestsWindowsX64)
    buildType(DockerTestsLinuxX64)
    buildType(DockerTestsLinuxArm64)
    buildType(RunAllDockerTests)
    buildType(PlatformTestsMacOSArm64)

    buildTypesOrder = arrayListOf(DockerTestsWindowsX64,DockerTestsLinuxX64,DockerTestsLinuxArm64,RunAllDockerTests,PlatformTestsMacOSArm64)

})
