// This file is automatically generated by `Build.ps1 generate-scripts`.

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildFeatures.*
import jetbrains.buildServer.configs.kotlin.buildSteps.*
import jetbrains.buildServer.configs.kotlin.failureConditions.*
import jetbrains.buildServer.configs.kotlin.triggers.*
import jetbrains.buildServer.configs.kotlin.projectFeatures.*
import buildTypes.*
import buildTypes.DockerTests.*

version = "2025.11"

project {

    buildType(DebugBuild)
    buildType(ReleaseBuild)
    buildType(PublicBuild)
    buildType(PublicDeployment)

    buildTypesOrder = arrayListOf(DebugBuild,ReleaseBuild,PublicBuild,PublicDeployment)

    subProject(DockerTests)

    subProjectsOrder = arrayListOf(DockerTests)

}

object DockerTests : Project({

    name = "Docker Tests"

    buildType(DockerTestsWindowsX64)
    buildType(DockerTestsLinuxX64)
    buildType(DockerTestsLinuxArm64)
    buildType(RunAllDockerTests)
    buildType(PlatformTestsMacOSArm64)

    buildTypesOrder = arrayListOf(DockerTestsWindowsX64,DockerTestsLinuxX64,DockerTestsLinuxArm64,RunAllDockerTests,PlatformTestsMacOSArm64)

})
