// This file is automatically generated by `Build.ps1 generate-scripts`.

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildFeatures.*
import jetbrains.buildServer.configs.kotlin.buildSteps.*
import jetbrains.buildServer.configs.kotlin.failureConditions.*
import jetbrains.buildServer.configs.kotlin.triggers.*
import jetbrains.buildServer.configs.kotlin.projectFeatures.*
import buildTypes.*
import buildTypes.PlatformTests.*

version = "2025.11"

project {

    buildType(DebugBuild)
    buildType(ReleaseBuild)
    buildType(PublicBuild)
    buildType(PublicDeployment)
    buildType(RunAllTestArchives)

    buildTypesOrder = arrayListOf(DebugBuild,ReleaseBuild,PublicBuild,PublicDeployment,RunAllTestArchives)

    subProject(PlatformTests)

    subProjectsOrder = arrayListOf(PlatformTests)

}

object PlatformTests : Project({

    name = "Platform Tests"

    buildType(PlatformTestsWinX64Net100)
    buildType(PlatformTestsLinuxX64Net100)
    buildType(PlatformTestsLinuxArm64Net100)
    buildType(PlatformTestsMacOSArm64Net100)

    buildTypesOrder = arrayListOf(PlatformTestsWinX64Net100,PlatformTestsLinuxX64Net100,PlatformTestsLinuxArm64Net100,PlatformTestsMacOSArm64Net100)

})
