// This file is automatically generated by `Build.ps1 generate-scripts`.

package buildTypes.PlatformTests

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildFeatures.*
import jetbrains.buildServer.configs.kotlin.buildSteps.*
import jetbrains.buildServer.configs.kotlin.failureConditions.*
import jetbrains.buildServer.configs.kotlin.triggers.*
import jetbrains.buildServer.configs.kotlin.projectFeatures.*
import buildTypes.*

object PlatformTestsMacOSArm64Net100 : BuildType({

    name = "Platform Tests macOS ARM64: net10.0"

    artifactRules = """+:artifacts/testResults/**/*=>artifacts/testResults"""

    params {
        text(
            "Exec.Arguments", 
            "", 
            label ="eng/RunTests.ps1 Arguments",
            description = "Arguments to append to the 'Execute eng/RunTests.ps1' build step.", allowEmpty = true)
        param("env.BACKSTAGE_PLATFORM_TEST_HOST", "host")
    }

    vcs {
        root(AbsoluteId("Backstage_Backstage20270"))
     checkoutMode = CheckoutMode.ON_AGENT
    }

    steps {
        powerShell {
            name = "Clean NuGet cache of produced and dependency packages"
            id = "CleanNuGetCache"
            edition = PowerShellStep.Edition.Core
            scriptMode = file {
                path = "eng/CleanUpBuildAgent.ps1"
            }
            noProfile = false
            scriptArgs = " "
        }
        powerShell {
            name = "Execute eng/RunTests.ps1"
            id = "Exec"
            edition = PowerShellStep.Edition.Core
            scriptMode = file {
                path = "eng/RunTests.ps1"
            }
            noProfile = false
            scriptArgs = "-Platform osx-arm64 %Exec.Arguments%"
        }
    }

    requirements {
        equals("teamcity.agent.jvm.os.name", "Mac OS X")
        equals("teamcity.agent.jvm.os.arch", "aarch64")
    }

    features {
        swabra {
            filesCleanup = Swabra.FilesCleanup.BEFORE_BUILD
            lockingProcesses = Swabra.LockingProcessPolicy.KILL
            verbose = true
        }
        gitHubAppBuildScopedToken {
            parameterName = "env.GITHUB_TOKEN"
            connectionId = "%GITHUB_CONNECTION_POSTSHARP_OPS%"
            targetRepositories = "SharpCrafters.Backstage"
        }
    }

    dependencies {
        snapshot(DebugBuild) {
                 onDependencyFailure = FailureAction.FAIL_TO_START
        }

        artifacts(DebugBuild) { 
            cleanDestination = true
            artifactRules = "+:artifacts/tests/SharpCrafters.Backstage.PlatformTests.net10.0.zip=>artifacts/tests"
        }
     }

})
