// This file is automatically generated by `Build.ps1 generate-scripts`.

package buildTypes.PlatformTests

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildFeatures.*
import jetbrains.buildServer.configs.kotlin.buildSteps.*
import jetbrains.buildServer.configs.kotlin.failureConditions.*
import jetbrains.buildServer.configs.kotlin.triggers.*
import jetbrains.buildServer.configs.kotlin.projectFeatures.*
import buildTypes.*

object PlatformTestsWinX64Net100 : BuildType({

    name = "Platform Tests Windows x64: net10.0"

    artifactRules = """+:artifacts/testResults/**/*=>artifacts/testResults"""

    params {
        text(
            "Exec.Arguments", 
            "", 
            label ="DockerBuild.ps1 Arguments",
            description = "Arguments to append to the 'Execute eng/RunTests.ps1' build step.", allowEmpty = true)
        param("env.BACKSTAGE_PLATFORM_TEST_HOST", "container")
    }

    vcs {
        root(AbsoluteId("Backstage_Backstage20270"))
     checkoutMode = CheckoutMode.ON_AGENT
    }

    steps {
        powerShell {
            name = "Clean NuGet cache of produced and dependency packages"
            id = "CleanNuGetCache"
            edition = PowerShellStep.Edition.Core
            scriptMode = file {
                path = "eng/CleanUpBuildAgent.ps1"
            }
            noProfile = false
            scriptArgs = "-DeferToContainer "
        }
        powerShell {
            name = "Prepare Docker image backstage-2027.0-platformtestswinx64net100"
            id = "PrepareImage"
            edition = PowerShellStep.Edition.Core
            scriptMode = file {
                path = "DockerBuild.ps1"
            }
            noProfile = false
            scriptArgs = "-BuildImage -ImageName backstage-2027.0-platformtestswinx64net100 -Dockerfile eng/docker/build.Dockerfile "
        }
        powerShell {
            name = "Execute eng/RunTests.ps1"
            id = "Exec"
            edition = PowerShellStep.Edition.Core
            scriptMode = file {
                path = "DockerBuild.ps1"
            }
            noProfile = false
            scriptArgs = "-Script eng/RunTests.ps1 -ImageName backstage-2027.0-platformtestswinx64net100 -Dockerfile eng/docker/build.Dockerfile -NoBuildImage -Label %system.teamcity.buildType.id%_%build.number% -Platform win-x64 %Exec.Arguments%"
        }
        powerShell {
            name = "Clean up the build agent"
            id = "DockerCleanup"
            executionMode = BuildStep.ExecutionMode.ALWAYS
            edition = PowerShellStep.Edition.Core
            scriptMode = file {
                path = "eng/CleanUpBuildAgent.ps1"
            }
            noProfile = false
            scriptArgs = "-After -BuildLabel %system.teamcity.buildType.id%_%build.number% "
        }
    }

    requirements {
        matches("teamcity.agent.jvm.os.family", "Windows")
        matches("teamcity.agent.jvm.os.arch", "amd64")
        equals("env.BuildAgentType", "docker-win-x64-md")
    }

    features {
        swabra {
            filesCleanup = Swabra.FilesCleanup.BEFORE_BUILD
            lockingProcesses = Swabra.LockingProcessPolicy.KILL
            verbose = true
        }
        gitHubAppBuildScopedToken {
            parameterName = "env.GITHUB_TOKEN"
            connectionId = "%GITHUB_CONNECTION_POSTSHARP_OPS%"
            targetRepositories = "SharpCrafters.Backstage"
        }
    }

    dependencies {
        snapshot(DebugBuild) {
                 onDependencyFailure = FailureAction.FAIL_TO_START
        }

        artifacts(DebugBuild) { 
            cleanDestination = true
            artifactRules = "+:artifacts/tests/SharpCrafters.Backstage.PlatformTests.net10.0.zip=>artifacts/tests"
        }
     }

})
