#!/usr/bin/env bash
# *** DO NOT EDIT THIS FILE DIRECTLY ***
# This file is auto-generated from src/PostSharp.Engineering.BuildTools/Resources/build.sh in the
# PostSharp.Engineering repository. Edit that file, then run `./Build.ps1 generate-scripts` to regenerate this one.

# Wrapper script to call Build.ps1 with PowerShell
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
pwsh -File "$SCRIPT_DIR/Build.ps1" "$@"
exit $?
