// Copyright (c) 2020-2025 SharpCrafters s.r.o. and contributors.
// SharpCrafters s.r.o. licenses this file to you under either the MIT license or a proprietary license, depending on the repository from which it was obtained.
// Refer to LICENSE.md in the repository root for complete details.

using JetBrains.Annotations;
using Metalama.Backstage.Extensibility;

namespace Metalama.Backstage.Infrastructure;

/// <summary>
/// Provides the identifier of the machine on which the current process runs.
/// </summary>
[PublicAPI]
public interface IMachineIdProvider : IBackstageService
{
    /// <summary>
    /// Gets an identifier of the current machine. The value is read from the operating system instead of being
    /// generated by the product, so it is the same in every process, for every user profile of the machine and in
    /// every version of the product.
    /// </summary>
    /// <remarks>
    /// <para>
    /// The value is intended to remain the same for the lifetime of the installation of the operating system, but
    /// this is a property of the identifiers that the operating systems report and not a guarantee of this interface.
    /// An administrator can replace the identifier reported by the operating system, and when no such identifier can
    /// be read, the implementation falls back to <see cref="System.Environment.MachineName"/>, which changes when the
    /// machine is renamed. The value is therefore not suitable for a purpose that requires a permanent identity.
    /// </para>
    /// <para>
    /// The license audit hashes this value to count the devices of one user, which the end-user license agreement
    /// limits. See issue #1873. This is not the anonymized device identifier reported to the third-party analytics
    /// platform, which is a random value rotated every month. See
    /// <see cref="Metalama.Backstage.Telemetry.ITelemetryConfigurationService.DeviceId"/>.
    /// </para>
    /// </remarks>
    string MachineId { get; }
}
