// Copyright (c) 2020-2025 SharpCrafters s.r.o. and contributors.
// SharpCrafters s.r.o. licenses this file to you under either the MIT license or a proprietary license, depending on the repository from which it was obtained.
// Refer to LICENSE.md in the repository root for complete details.

using Metalama.Backstage.Commands.Configuration;
using Metalama.Backstage.Commands.Licensing;
using Metalama.Backstage.Commands.Maintenance;
using Metalama.Backstage.Commands.Misc;
using Metalama.Backstage.Commands.Rss;
using Metalama.Backstage.Commands.Telemetry;
using Metalama.Backstage.Commands.UserInterface;
using Spectre.Console.Cli;
using System;

namespace Metalama.Backstage.Commands;

public static class BackstageCommandFactory
{
    public static void ConfigureCommandApp(
        CommandApp app,
        BackstageCommandOptions options,
        Action<IConfigurator>? configureMoreCommands = null,
        Action<string, IConfigurator<CommandSettings>>? configureBranch = null )
    {
        app.Configure(
            appConfig =>
            {
                appConfig.AddBranch(
                    "license",
                    license =>
                    {
                        license.SetDescription( "Manages license keys and switch between Metalama editions." );

                        license.AddCommand<ListLicensesCommand>( "list" )
                            .WithData( options )
                            .WithDescription( "Lists all registered licenses." );

                        license.AddCommand<RegisterLicenseCommand>( "register" )
                            .WithData( options )
                            .WithDescription( "Registers a new license key." );

                        license.AddCommand<UnregisterCommand>( "unregister" )
                            .WithData( options )
                            .WithDescription( "Unregisters all license keys." );

                        license.AddCommand<RegisterTrialCommand>( "try" )
                            .WithData( options )
                            .WithDescription( "Activates the Metalama trial period." );

                        license.AddCommand<RegisterCommunityCommand>( "community" )
                            .WithData( options )
                            .WithDescription( "Switches to the Metalama Community edition." );

#pragma warning disable CS0612 // Type or member is obsolete
                        license.AddCommand<RegisterLegacyFreeCommand>( "free" )
                            .WithData( options )
                            .WithDescription( "Registers the legacy Metalama Free license (for Metalama 2025.0 and earlier)." );
#pragma warning restore CS0612 // Type or member is obsolete

                        configureBranch?.Invoke( "license", license );
                    } );

                appConfig.AddBranch(
                    "config",
                    config =>
                    {
                        config.SetDescription( "Manages Metalama configuration settings." );

                        config.AddCommand<ListConfigurationsCommand>( "list" )
                            .WithData( options )
                            .WithDescription( "Lists all supported JSON configuration files." );

                        config.AddCommand<EditConfigurationCommand>( "edit" )
                            .WithData( options )
                            .WithDescription( "Opens a JSON configuration file in the default text editor." );

                        config.AddCommand<ResetConfigurationCommand>( "reset" )
                            .WithData( options )
                            .WithDescription( "Resets a configuration file to its default values." );

                        config.AddCommand<PrintConfigurationCommand>( "print" )
                            .WithData( options )
                            .WithDescription( "Displays the contents of a configuration file in the console." );

                        config.AddCommand<ValidateConfigurationCommand>( "validate" )
                            .WithData( options )
                            .WithDescription( "Validates a configuration file against its schema." );

                        configureBranch?.Invoke( "config", config );
                    } );

                appConfig.AddCommand<CleanUpCommand>( "cleanup" )
                    .WithData( options )
                    .WithDescription( "Removes temporary files and cache generated by Metalama." );

                appConfig.AddCommand<KillCommand>( "kill" )
                    .WithData( options )
                    .WithDescription( "Terminates processes that may be locking Metalama packages." );

                appConfig.AddBranch(
                    "telemetry",
                    telemetry =>
                    {
                        telemetry.SetDescription( "Manages telemetry settings and upload queued data." );

                        telemetry.AddCommand<EnableTelemetryCommand>( "enable" ).WithData( options ).WithDescription( "Enables anonymous usage telemetry." );
                        telemetry.AddCommand<DisableTelemetryCommand>( "disable" ).WithData( options ).WithDescription( "Disables anonymous usage telemetry." );

                        telemetry.AddCommand<ResetDeviceIdCommand>( "reset-device-id" )
                            .WithDescription( "Generates a new anonymous device identifier for telemetry." );

                        telemetry.AddCommand<UploadTelemetryCommand>( "upload" )
                            .WithData( options )
                            .WithDescription( "Uploads all queued telemetry data immediately." );

                        telemetry.AddCommand<TelemetryStatusCommand>( "status" )
                            .WithData( options )
                            .WithDescription( "Displays current telemetry configuration and status." );

                        configureBranch?.Invoke( "telemetry", telemetry );
                    } );

                appConfig.AddCommand<DocsCommand>( "docs" ).WithData( options ).WithDescription( "Opens the Metalama documentation in your browser." );
                appConfig.AddCommand<OpenUICommand>( "ui" ).WithData( options ).WithDescription( "Opens the browser-based configuration interface." );

                appConfig.AddBranch(
                    "news",
                    rss =>
                    {
                        rss.SetDescription( "Manages toast notifications for new Metalama updates." );
                        
                        rss.AddCommand<DisplayLatestNewsCommand>( "notify" )
                            .WithData( options )
                            .WithDescription( "Displays a notification with the latest Metalama news." );
                        
                        rss.AddCommand<DisableRssClientCommand>( "disable" )
                            .WithData( options )
                            .WithDescription( "Disables automatic notifications for new Metalama updates." );
                        
                        rss.AddCommand<EnableRssClientCommand>( "enable" )
                            .WithData( options )
                            .WithDescription( "Enables automatic notifications for new Metalama updates." );
                    } );


                appConfig.AddCommand<VersionCommand>( "version" ).WithData( options ).WithDescription( "Prints version information." );

                configureMoreCommands?.Invoke( appConfig );
            } );
    }
}