# *** DO NOT EDIT THIS FILE DIRECTLY ***
# This file is auto-generated from src/PostSharp.Engineering.BuildTools/Resources/CleanUpBuildAgent.ps1 in the
# PostSharp.Engineering repository. Edit that file, then run `./Build.ps1 generate-scripts` to regenerate this one.
# Documentation: https://raw.githubusercontent.com/postsharp/PostSharp.Engineering/HEAD/doc/dockerbuild.md

<#
.SYNOPSIS
    Cleans up what a build leaves behind on a build agent.

.DESCRIPTION
    Two jobs, one script, because both answer the same question -- what does one build leave behind that the
    next build must not see -- and because a build step that names a script keeps the generated TeamCity
    settings free of long inline commands.

    BEFORE the build (the default), it deletes the stale packages of this product from the NuGet cache. Every
    continuous-integration build of a product carries the same public package version, and NuGet never extracts
    a version that is already in the global packages folder, so a build that does not delete the previous copy
    restores that copy instead of the artifacts it depends on -- and a test that passes then proves nothing
    about the code under test.

    AFTER the build (-After), it removes the containers the build started and gives the agent a chance to undo
    what those containers did to the working directory.

.PARAMETER After
    Runs the post-build clean-up instead of the pre-build one: the containers of this build, then the command
    the agent names in BUILDAGENT_CLEANUP_SCRIPT. This is hygiene, so it reports what fails and never fails the
    build: a build that would otherwise pass should not be failed by it.

.PARAMETER InContainer
    States that the caller is a container that mounts the NuGet cache. Such a caller runs as root, so it is the
    last thing that can remove these directories and every survivor is a defect.

.PARAMETER DeferToContainer
    States that this build restores inside a container, which will run this script as root before it restores. A
    directory belonging to another account is then named and left to that container, because no error handling on
    an agent can unlink what a container extracted, and failing here would mean no build could ever run again on
    such an agent.

    Without it every survivor fails the build, which is the answer for a build that restores on the agent itself:
    there is no later container to defer to, so deferring would let the build restore the very package the
    clean-up exists to remove. -InContainer overrides it, a container having nobody to defer to either.

.PARAMETER BuildLabel
    With -After, the value of the `postsharp.build` label that identifies the containers of this build. Unset
    removes nothing, rather than removing the containers of a build that is still running.

.PARAMETER NuGetCacheDirectory
    The global packages folder to clean. Defaults to NUGET_PACKAGES, and to $HOME/.nuget/packages when that is
    unset, which is how NuGet itself resolves it.

.PARAMETER EmitTestCommandPrefix
    Writes the POSIX shell command that a test container runs in place of this script, and does nothing else. A
    test image is chosen for the tool chain under test and is not required to carry PowerShell, so a test
    container cannot run this script at all; DockerBuild.ps1 asks for the command here so that the list of
    packages and the way they are deleted stay in one place.

.EXAMPLE
    ./eng/CleanUpBuildAgent.ps1
    Deletes the stale packages, as the first step of a build does.

.EXAMPLE
    ./eng/CleanUpBuildAgent.ps1 -After -BuildLabel MyProject_Build_123
    Removes the containers of that build and runs the agent's clean-up command.
#>

param(
    [switch]$After,
    [switch]$InContainer,
    [switch]$DeferToContainer,
    [string]$BuildLabel,
    [string]$NuGetCacheDirectory,
    [switch]$EmitTestCommandPrefix
)

####
# These settings are replaced by the generate-scripts command.
# The packages this product produces, those of the whole closure of its package dependencies, and those of its
# source dependencies with their own closures: everything the build can reach and therefore everything whose
# stale copy it could restore. Ordered and deduplicated by the SDK, so this list is stable between runs.
$NuGetCachePackagePatterns = @('metalama.backstage*', 'postsharp.backstage*', 'postsharp.engineering', 'postsharp.engineering.*', 'sharpcrafters.backstage*', 'sharpcrafters.common*')
####

$ErrorActionPreference = 'Stop'

# Detect the platform. Windows PowerShell defines neither of these.
if ($null -eq $IsWindows)
{
    $IsWindows = [System.Environment]::OSVersion.Platform -eq [System.PlatformID]::Win32NT
}

$IsUnix = -not $IsWindows

# Where NuGet extracts the packages, resolved the way NuGet resolves it.
function Get-NuGetCacheDirectory
{
    if ($NuGetCacheDirectory)
    {
        return $NuGetCacheDirectory
    }

    if ($env:NUGET_PACKAGES)
    {
        return $env:NUGET_PACKAGES
    }

    return Join-Path $HOME '.nuget' 'packages'
}

# The identifier of the account this script runs as, or $null where the question does not arise. It decides
# whether a directory that cannot be removed is a defect or one that belongs to root and that a container will
# remove: only another account's directories are the container's to deal with.
function Get-OwnUserId
{
    if ($IsWindows)
    {
        return $null
    }

    try
    {
        # `id` is on every Unix. A machine without it gets the Windows treatment, where every survivor is a defect.
        return [int](& id -u)
    }
    catch
    {
        return $null
    }
}

# Whether anything still under $path belongs to an account other than $ownUserId. The whole tree is tested rather
# than the directory itself: NuGet creates the directory of a package the first time anything restores it, so the
# agent may well own that while the version directory a container extracted underneath it belongs to root.
function Test-OwnedByAnotherAccount([string]$path, $ownUserId)
{
    if ($null -eq $ownUserId)
    {
        return $false
    }

    $entries = @(Get-Item -LiteralPath $path -Force -ErrorAction SilentlyContinue) +
            @(Get-ChildItem -LiteralPath $path -Recurse -Force -ErrorAction SilentlyContinue)

    return @($entries | Where-Object { $_.UnixStat.UserId -ne $ownUserId }).Count -gt 0
}

# The command a test container runs in place of this script. `rm -rf` has exactly the wanted semantics at both
# ends: a pattern that matches nothing is silently fine, and a directory it cannot remove makes it exit non-zero,
# so the `&&` that follows keeps the test command from running at all. The directory is quoted and the pattern is
# not, which is what leaves the pattern for the shell to expand; the SDK refuses a pattern holding anything but a
# package identifier and the `*` wildcard.
function New-TestCommandPrefix([string]$nugetCacheDirectory)
{
    if ($NuGetCachePackagePatterns.Count -eq 0 -or [string]::IsNullOrEmpty($nugetCacheDirectory))
    {
        return ""
    }

    # The POSIX way to put an apostrophe in a single-quoted word: end the quoting, escape the apostrophe, resume.
    $quotedDirectory = "'" + ( $nugetCacheDirectory -replace "'", "'\''" ) + "'"
    $words = $NuGetCachePackagePatterns | ForEach-Object { "$quotedDirectory/$_" }

    return "rm -rf " + ( $words -join ' ' ) + " && "
}

# Deletes the stale packages of this product. Returns nothing and sets the exit code: 0 when the cache holds none
# of them, which is the normal state of a freshly cleaned agent, and 1 when one that should have gone is still
# there. Restoring a stale package is worse than not building at all, because it reports a pass for code that was
# never tested.
function Remove-StalePackages
{
    $nugetCacheDirectory = Get-NuGetCacheDirectory

    if (-not (Test-Path -LiteralPath $nugetCacheDirectory))
    {
        Write-Host "The NuGet packages folder does not exist: $nugetCacheDirectory"

        return 0
    }

    $ownUserId = Get-OwnUserId
    $removedDirectories = 0
    $removedFiles = 0
    $failures = @()
    $ownedByAnotherAccount = @()

    foreach ($pattern in $NuGetCachePackagePatterns)
    {
        foreach ($directory in @(Get-ChildItem -LiteralPath $nugetCacheDirectory -Directory -Filter $pattern -ErrorAction SilentlyContinue))
        {
            $path = $directory.FullName
            $files = @(Get-ChildItem -LiteralPath $path -Recurse -File -ErrorAction SilentlyContinue).Count
            Write-Host "Removing NuGet cache directory: $path ($files file(s))"

            $failure = $null

            try
            {
                Remove-Item -LiteralPath $path -Recurse -Force -ErrorAction Stop
            }
            catch
            {
                $failure = $_.Exception.Message
            }

            if (-not (Test-Path -LiteralPath $path))
            {
                $removedDirectories++
                $removedFiles += $files
                continue
            }

            if (-not $failure)
            {
                $failure = 'the directory is still present after the removal'
            }

            # Deferring is only honest when something else really will remove it: a container of this build, which
            # runs as root and runs this script before it restores. A build that restores on the agent itself has no
            # such container, and deferring there would let it restore the very package this deletes. A container has
            # nobody to defer to at all.
            if ($DeferToContainer -and -not $InContainer -and (Test-OwnedByAnotherAccount $path $ownUserId))
            {
                $ownedByAnotherAccount += $path
            }
            else
            {
                $failures += "${path}: $failure"
            }
        }
    }

    Write-Host "Removed $removedDirectories package directory(ies) and $removedFiles file(s) from the NuGet cache."

    if ($ownedByAnotherAccount.Count -gt 0)
    {
        Write-Host ("$( $ownedByAnotherAccount.Count ) directory(ies) belong to another account, having been extracted by a " +
                "container of an earlier build. The container that restores them next deletes them, and fails the build if it cannot:")
        $ownedByAnotherAccount | ForEach-Object { Write-Host "  $_" }
    }

    if ($failures.Count -gt 0)
    {
        Write-Host "The NuGet cache could not be cleaned, so this build would restore stale packages:" -ForegroundColor Red
        $failures | ForEach-Object { Write-Host "  $_" -ForegroundColor Red }

        return 1
    }

    return 0
}

# Removes the containers this build started, then lets the agent undo what they did to the working directory.
#
# A container runs as root while the agent does not, and the repository is a bind mount, so whatever the build
# wrote into it is owned by root on the host. The agent user cannot unlink those files, and a checkout directory
# belongs to a VCS root rather than to one build configuration, so the next build OF ANY KIND on that agent fails
# at checkout with "Error while applying patch" and thousands of "failed to remove ...: Permission denied".
#
# The containers go first, so that nothing is still writing when the agent's command runs. What that command is,
# is the agent's business: BUILDAGENT_CLEANUP_SCRIPT names it -- typically "sudo /opt/buildAgent/bin/chown-all.sh"
# on the Linux agents -- and unset means no command, which is every Windows agent, where the question does not
# arise.
function Remove-BuildLeftovers
{
    if ($BuildLabel)
    {
        $containers = @(docker ps -a -q --filter "label=postsharp.build=$BuildLabel")

        if ($containers.Count -gt 0)
        {
            Write-Host "Removing $( $containers.Count ) container(s) of this build."
            docker rm -f @containers 2>&1 | Out-Null
        }
    }
    else
    {
        # Removing every container of the agent would take out a build running beside this one.
        Write-Host "No build label was given, so no container is removed."
    }

    if ($env:BUILDAGENT_CLEANUP_SCRIPT)
    {
        Write-Host "Running the agent cleanup script: $( $env:BUILDAGENT_CLEANUP_SCRIPT )"

        try
        {
            Invoke-Expression $env:BUILDAGENT_CLEANUP_SCRIPT

            if ($LASTEXITCODE -ne 0)
            {
                Write-Host "The agent cleanup script exited with code $LASTEXITCODE."
            }
        }
        catch
        {
            Write-Host "The agent cleanup script failed: $_"
        }
    }

    # Hygiene: a build that would otherwise pass is not failed by it.
    return 0
}

if ($EmitTestCommandPrefix)
{
    New-TestCommandPrefix (Get-NuGetCacheDirectory)
    exit 0
}

if ($After)
{
    if ($InContainer)
    {
        # The post-build clean-up removes containers and runs a command of the host. Neither is a container's to do.
        Write-Host "-After cannot be combined with -InContainer." -ForegroundColor Red
        exit 1
    }

    exit (Remove-BuildLeftovers)
}

exit (Remove-StalePackages)
