// This file is automatically generated by `Build.ps1 generate-scripts`.

package buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildFeatures.*
import jetbrains.buildServer.configs.kotlin.buildSteps.*
import jetbrains.buildServer.configs.kotlin.failureConditions.*
import jetbrains.buildServer.configs.kotlin.triggers.*
import jetbrains.buildServer.configs.kotlin.projectFeatures.*
import buildTypes.DockerTests.*

object PublicDeployment : BuildType({

    name = "Deploy [Public]"

    type = Type.DEPLOYMENT

    params {
        text(
            "Publish.Arguments", 
            "", 
            label ="DockerBuild.ps1 Arguments",
            description = "Arguments to append to the 'Publish' build step.", allowEmpty = true)
        param("Publish.Timeout", "30")
    }

    vcs {
        root(AbsoluteId("Backstage_Backstage20270"))
     checkoutMode = CheckoutMode.ON_AGENT
    }

    steps {
        powerShell {
            name = "Clean NuGet cache of produced and dependency packages"
            id = "CleanNuGetCache"
            edition = PowerShellStep.Edition.Core
            scriptMode = file {
                path = "eng/CleanUpBuildAgent.ps1"
            }
            noProfile = false
            scriptArgs = "-DeferToContainer "
        }
        powerShell {
            name = "Prepare Docker image backstage-2027.0"
            id = "PrepareImage"
            edition = PowerShellStep.Edition.Core
            scriptMode = file {
                path = "DockerBuild.ps1"
            }
            noProfile = false
            scriptArgs = "-BuildImage -ImageName backstage-2027.0 "
        }
        powerShell {
            name = "Publish"
            id = "Publish"
            edition = PowerShellStep.Edition.Core
            scriptMode = file {
                path = "DockerBuild.ps1"
            }
            noProfile = false
            scriptArgs = "-Script Build.ps1 -ImageName backstage-2027.0 -NoBuildImage -Label %system.teamcity.buildType.id%_%build.number% publish --configuration Public --deployment default --timeout %Publish.Timeout% %Publish.Arguments%"
        }
        powerShell {
            name = "Clean up the build agent"
            id = "DockerCleanup"
            executionMode = BuildStep.ExecutionMode.ALWAYS
            edition = PowerShellStep.Edition.Core
            scriptMode = file {
                path = "eng/CleanUpBuildAgent.ps1"
            }
            noProfile = false
            scriptArgs = "-After -BuildLabel %system.teamcity.buildType.id%_%build.number% "
        }
    }

    requirements {
        matches("teamcity.agent.jvm.os.family", "Windows")
        matches("teamcity.agent.jvm.os.arch", "amd64")
        equals("env.BuildAgentType", "docker-win-x64-md")
    }

    features {
        swabra {
            filesCleanup = Swabra.FilesCleanup.BEFORE_BUILD
            lockingProcesses = Swabra.LockingProcessPolicy.KILL
            verbose = true
        }
        gitHubAppBuildScopedToken {
            parameterName = "env.GITHUB_TOKEN"
            connectionId = "%GITHUB_CONNECTION_POSTSHARP_OPS%"
            targetRepositories = "SharpCrafters.Backstage"
        }
    }

    dependencies {
        snapshot(PublicBuild) {
                 onDependencyFailure = FailureAction.FAIL_TO_START
        }

        artifacts(PublicBuild) { 
            cleanDestination = true
            artifactRules = "+:artifacts/publish/public/**/*=>artifacts/publish/public\n+:artifacts/publish/private/**/*=>artifacts/publish/private"
        }
     }

})
