// This file is automatically generated by `Build.ps1 generate-scripts`.

package buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildFeatures.*
import jetbrains.buildServer.configs.kotlin.buildSteps.*
import jetbrains.buildServer.configs.kotlin.failureConditions.*
import jetbrains.buildServer.configs.kotlin.triggers.*
import jetbrains.buildServer.configs.kotlin.projectFeatures.*
import buildTypes.DockerTests.*

object ReleaseBuild : BuildType({

    name = "Build [Release]"

    artifactRules = """+:artifacts/publish/public/**/*=>artifacts/publish/public
+:artifacts/publish/private/**/*=>artifacts/publish/private
+:artifacts/testResults/**/*=>artifacts/testResults
+:artifacts/logs/**/*=>logs
+:artifacts/dumps/**/*=>dumps
"""

    params {
        text(
            "Build.Arguments", 
            "", 
            label ="DockerBuild.ps1 Arguments",
            description = "Arguments to append to the 'Build' build step.", allowEmpty = true)
        param("Build.Timeout", "30")
    }

    vcs {
        root(AbsoluteId("Backstage_Backstage20270"))
     checkoutMode = CheckoutMode.ON_AGENT
    }

    steps {
        powerShell {
            name = "Clean NuGet cache of produced and dependency packages"
            id = "CleanNuGetCache"
            edition = PowerShellStep.Edition.Core
            scriptMode = file {
                path = "eng/CleanUpBuildAgent.ps1"
            }
            noProfile = false
            scriptArgs = "-DeferToContainer "
        }
        powerShell {
            name = "Prepare Docker image backstage-2027.0"
            id = "PrepareImage"
            edition = PowerShellStep.Edition.Core
            scriptMode = file {
                path = "DockerBuild.ps1"
            }
            noProfile = false
            scriptArgs = "-BuildImage -ImageName backstage-2027.0 "
        }
        powerShell {
            name = "Build"
            id = "Build"
            edition = PowerShellStep.Edition.Core
            scriptMode = file {
                path = "DockerBuild.ps1"
            }
            noProfile = false
            scriptArgs = "-Script Build.ps1 -ImageName backstage-2027.0 -NoBuildImage -Label %system.teamcity.buildType.id%_%build.number% test --configuration Release --buildNumber %build.number% --buildType %system.teamcity.buildType.id% --timeout %Build.Timeout% %Build.Arguments%"
        }
        powerShell {
            name = "Clean up the build agent"
            id = "DockerCleanup"
            executionMode = BuildStep.ExecutionMode.ALWAYS
            edition = PowerShellStep.Edition.Core
            scriptMode = file {
                path = "eng/CleanUpBuildAgent.ps1"
            }
            noProfile = false
            scriptArgs = "-After -BuildLabel %system.teamcity.buildType.id%_%build.number% "
        }
    }

    requirements {
        matches("teamcity.agent.jvm.os.family", "Windows")
        matches("teamcity.agent.jvm.os.arch", "amd64")
        equals("env.BuildAgentType", "docker-win-x64-md")
    }

    features {
        swabra {
            filesCleanup = Swabra.FilesCleanup.BEFORE_BUILD
            lockingProcesses = Swabra.LockingProcessPolicy.KILL
            verbose = true
        }
        gitHubAppBuildScopedToken {
            parameterName = "env.GITHUB_TOKEN"
            connectionId = "%GITHUB_CONNECTION_POSTSHARP_OPS%"
            targetRepositories = "SharpCrafters.Backstage"
        }
        commitStatusPublisher {
            vcsRootExtId = "Backstage_Backstage20270"
            publisher = github {
                githubUrl = "https://api.github.com"
                authType = vcsRoot()
            }
        }
        pullRequests {
            vcsRootExtId = "Backstage_Backstage20270"
            provider = github {
                authType = vcsRoot()
                filterTargetBranch = "+:refs/heads/develop/2027.0"
                filterAuthorRole = PullRequests.GitHubRoleFilter.EVERYBODY
            }
        }
    }

})
