// This file is automatically generated by `Build.ps1 generate-scripts`.

package buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildFeatures.*
import jetbrains.buildServer.configs.kotlin.buildSteps.*
import jetbrains.buildServer.configs.kotlin.failureConditions.*
import jetbrains.buildServer.configs.kotlin.triggers.*
import jetbrains.buildServer.configs.kotlin.projectFeatures.*
import buildTypes.PlatformTests.*

object RunAllTestArchives : BuildType({

    name = "Run All Test Archives"

    type = Type.COMPOSITE

    vcs {
        root(AbsoluteId("Backstage_Backstage20270"))
        showDependenciesChanges = true
     checkoutMode = CheckoutMode.ON_AGENT
    }

    features {
        gitHubAppBuildScopedToken {
            parameterName = "env.GITHUB_TOKEN"
            connectionId = "%GITHUB_CONNECTION_POSTSHARP_OPS%"
            targetRepositories = "SharpCrafters.Backstage"
        }
    }

    dependencies {
        snapshot(PlatformTestsWinX64Net100) {
                 onDependencyFailure = FailureAction.FAIL_TO_START
        }
        snapshot(PlatformTestsLinuxX64Net100) {
                 onDependencyFailure = FailureAction.FAIL_TO_START
        }
        snapshot(PlatformTestsLinuxArm64Net100) {
                 onDependencyFailure = FailureAction.FAIL_TO_START
        }
        snapshot(PlatformTestsMacOSArm64Net100) {
                 onDependencyFailure = FailureAction.FAIL_TO_START
        }
     }

})
