<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>netframework4.7.2;net10.0;netstandard2.0</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>SharpCrafters.Backstage</RootNamespace>
    </PropertyGroup>

</Project>
