// This file is automatically generated by `Build.ps1 generate-scripts`.

package buildTypes.DockerTests

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildFeatures.*
import jetbrains.buildServer.configs.kotlin.buildSteps.*
import jetbrains.buildServer.configs.kotlin.failureConditions.*
import jetbrains.buildServer.configs.kotlin.triggers.*
import jetbrains.buildServer.configs.kotlin.projectFeatures.*
import buildTypes.*

object PlatformTestsMacOSArm64 : BuildType({

    name = "Platform Tests (macOS ARM64)"

    params {
        text(
            "Exec.Arguments", 
            "", 
            label ="src/tests/Platform/RunMacOSTests.ps1 Arguments",
            description = "Arguments to append to the 'Execute src/tests/Platform/RunMacOSTests.ps1' build step.", allowEmpty = true)
    }

    vcs {
        root(AbsoluteId("Backstage_Backstage20270"))
     checkoutMode = CheckoutMode.ON_AGENT
    }

    steps {
        powerShell {
            name = "Clean NuGet cache of produced and dependency packages"
            id = "CleanNuGetCache"
            edition = PowerShellStep.Edition.Core
            scriptMode = file {
                path = "eng/CleanUpBuildAgent.ps1"
            }
            noProfile = false
            scriptArgs = " "
        }
        powerShell {
            name = "Copy nuget.restored.config to nuget.config"
            id = "CopyNuGetConfig"
            edition = PowerShellStep.Edition.Core
            scriptMode = script {
                content = "Copy-Item -Path \"artifacts/publish/private/nuget.restored.config\" -Destination \"nuget.config\" -Force;Copy-Item -Path \"artifacts/publish/private/nuget.restored.config\" -Destination \"nuget.wsl.config\" -Force;"
            }
            noProfile = false
        }
        powerShell {
            name = "Create eng/Versions.g.props"
            id = "CreateVersionsFile"
            edition = PowerShellStep.Edition.Core
            scriptMode = script {
                content = "New-Item -Path \"eng/Versions.g.props\" -ItemType File -Force -Value \"<Project><Import Project=`\"../artifacts/publish/private/Backstage.version.props`\" /></Project>\" | Out-Null;"
            }
            noProfile = false
        }
        powerShell {
            name = "Execute src/tests/Platform/RunMacOSTests.ps1"
            id = "Exec"
            edition = PowerShellStep.Edition.Core
            scriptMode = file {
                path = "src/tests/Platform/RunMacOSTests.ps1"
            }
            noProfile = false
            scriptArgs = " %Exec.Arguments%"
        }
    }

    requirements {
        equals("teamcity.agent.jvm.os.name", "Mac OS X")
        equals("teamcity.agent.jvm.os.arch", "aarch64")
    }

    features {
        swabra {
            filesCleanup = Swabra.FilesCleanup.BEFORE_BUILD
            lockingProcesses = Swabra.LockingProcessPolicy.KILL
            verbose = true
        }
        gitHubAppBuildScopedToken {
            parameterName = "env.GITHUB_TOKEN"
            connectionId = "%GITHUB_CONNECTION_POSTSHARP_OPS%"
            targetRepositories = "SharpCrafters.Backstage"
        }
    }

    dependencies {
        snapshot(DebugBuild) {
                 onDependencyFailure = FailureAction.FAIL_TO_START
        }

        artifacts(DebugBuild) { 
            cleanDestination = true
            artifactRules = "+:artifacts/publish/private/**/*=>artifacts/publish/private"
        }
     }

})
