// This file is automatically generated by `Build.ps1 generate-scripts`.

package buildTypes.DockerTests

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildFeatures.*
import jetbrains.buildServer.configs.kotlin.buildSteps.*
import jetbrains.buildServer.configs.kotlin.failureConditions.*
import jetbrains.buildServer.configs.kotlin.triggers.*
import jetbrains.buildServer.configs.kotlin.projectFeatures.*
import buildTypes.*

object RunAllDockerTests : BuildType({

    name = "Run All Docker Tests"

    type = Type.COMPOSITE

    vcs {
        root(AbsoluteId("Backstage_Backstage20270"))
        showDependenciesChanges = true
     checkoutMode = CheckoutMode.ON_AGENT
    }

    features {
        gitHubAppBuildScopedToken {
            parameterName = "env.GITHUB_TOKEN"
            connectionId = "%GITHUB_CONNECTION_POSTSHARP_OPS%"
            targetRepositories = "SharpCrafters.Backstage"
        }
    }

    dependencies {
        snapshot(DockerTestsWindowsX64) {
                 onDependencyFailure = FailureAction.FAIL_TO_START
        }
        snapshot(DockerTestsLinuxX64) {
                 onDependencyFailure = FailureAction.FAIL_TO_START
        }
        snapshot(DockerTestsLinuxArm64) {
                 onDependencyFailure = FailureAction.FAIL_TO_START
        }
     }

})
