<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <IsPackable>false</IsPackable>
        <RootNamespace>SharpCrafters.Backstage.LicenseServerLoadSimulator</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Metalama.Backstage\Metalama.Backstage.csproj"/>
        <ProjectReference Include="..\..\tests\SharpCrafters.Backstage.Testing\SharpCrafters.Backstage.Testing.csproj"/>
    </ItemGroup>

</Project>
